version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      target: python
    volumes:
      - static_volume:/home/webapp/static
      - media_volume:/home/webapp/media
      - run:/home/webapp/run
    command: bin/gunicorn_start.sh
    ports:
      - 8080:8000
    env_file:
      - .env.web
    depends_on:
      - db
    container_name: container-python
  db:
    restart: always
    image: postgres:11.4-alpine
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: container-postgres
  nginx:
    restart: always
    build:
      context: .
      target: nginx
    volumes:
      - static_volume:/home/webapp/static
      - media_volume:/home/webapp/media
      - run:/home/webapp/run
    ports:
      - "80:80"
    depends_on:
      - web
    container_name: container-nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  run:
